# Generated by Django 4.2.13 on 2024-05-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_author_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-published_year']},
        ),
    ]
