# Generated by Django 5.0.6 on 2024-08-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_bookshelf_notes_alter_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='quotes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='style',
            field=models.CharField(choices=[('audiobook', 'Audiobook'), ('kindle', 'Kindle'), ('paper', 'Paper')], default='paper', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
