# Generated by Django 5.0.6 on 2024-08-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_bookshelf_quotes_bookshelf_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='date_read',
            field=models.DateField(blank=True, null=True),
        ),
    ]
