# Generated by Django 5.0.6 on 2024-07-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='about_us',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
