# Generated by Django 4.2.13 on 2024-06-20 18:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
