# Generated by Django 4.2.13 on 2024-06-24 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_request', '0002_alter_bookrequest_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
