# Generated by Django 4.2.13 on 2024-06-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_request', '0003_bookrequest_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequest',
            name='cover_image',
        ),
    ]
