# Generated by Django 5.0.6 on 2024-07-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_request', '0004_remove_bookrequest_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='published_year',
            field=models.IntegerField(max_length=60),
        ),
    ]
