# Generated by Django 5.0.6 on 2024-07-16 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_request', '0005_alter_bookrequest_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='published_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999), django.core.validators.RegexValidator(code='invalid_year', message='Year cannot be more than 4 digits', regex='^\\d{4}$')]),
        ),
    ]
